// https://syzkaller.appspot.com/bug?id=90ee9f6738daa68f079c010624c70fca59b2f2cd
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <sys/types.h>

#include <pwd.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/endian.h>
#include <sys/syscall.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

static void kill_and_wait(int pid, int* status)
{
  kill(pid, SIGKILL);
  while (waitpid(-1, status, 0) != pid) {
  }
}

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void execute_one(void);

#define WAIT_FLAGS 0

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000) {
        continue;
      }
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  res = syscall(SYS_socket, 0x1cul, 5ul, 0x84);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000300 = 0x200;
  syscall(SYS_setsockopt, r[0], 0xffff, 0x1001, 0x20000300ul, 4ul);
  *(uint32_t*)0x20000000 = 0x804;
  syscall(SYS_setsockopt, r[0], 0x84, 0x1b, 0x20000000ul, 4ul);
  *(uint64_t*)0x20000480 = 0x20000080;
  *(uint8_t*)0x20000080 = 0x1c;
  *(uint8_t*)0x20000081 = 0x1c;
  *(uint16_t*)0x20000082 = htobe16(0x4e23);
  *(uint32_t*)0x20000084 = 0;
  *(uint64_t*)0x20000088 = htobe64(0);
  *(uint64_t*)0x20000090 = htobe64(1);
  *(uint32_t*)0x20000098 = 0;
  *(uint32_t*)0x20000488 = 0x1c;
  *(uint64_t*)0x20000490 = 0x200000c0;
  *(uint64_t*)0x200000c0 = 0x20000200;
  memset((void*)0x20000200, 115, 1);
  *(uint64_t*)0x200000c8 = 1;
  *(uint64_t*)0x200000d0 = 0;
  *(uint64_t*)0x200000d8 = 0;
  *(uint32_t*)0x20000498 = 2;
  *(uint64_t*)0x200004a0 = 0;
  *(uint32_t*)0x200004a8 = 0;
  *(uint32_t*)0x200004ac = 0;
  syscall(SYS_sendmsg, r[0], 0x20000480ul, 0ul);
  *(uint64_t*)0x20000280 = 0x20000100;
  *(uint8_t*)0x20000100 = 0x1c;
  *(uint8_t*)0x20000101 = 0x1c;
  *(uint16_t*)0x20000102 = htobe16(0x4e23);
  *(uint32_t*)0x20000104 = 0;
  *(uint64_t*)0x20000108 = htobe64(0);
  *(uint64_t*)0x20000110 = htobe64(1);
  *(uint32_t*)0x20000118 = 0;
  *(uint32_t*)0x20000288 = 0x1c;
  *(uint64_t*)0x20000290 = 0x20000240;
  *(uint64_t*)0x20000240 = 0x20000140;
  memset((void*)0x20000140, 51, 1);
  *(uint64_t*)0x20000248 = 1;
  *(uint32_t*)0x20000298 = 1;
  *(uint64_t*)0x200002a0 = 0;
  *(uint32_t*)0x200002a8 = 0;
  *(uint32_t*)0x200002ac = 0;
  syscall(SYS_sendmsg, r[0], 0x20000280ul, 0ul);
}
int main(void)
{
  syscall(SYS_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x1012ul, -1, 0ul);
  loop();
  return 0;
}
