// https://syzkaller.appspot.com/bug?id=10e5ff4a294e585d65a9e8e0211b2751ac108462
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <sys/types.h>

#include <dirent.h>
#include <errno.h>
#include <pthread.h>
#include <pwd.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/endian.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

static unsigned long long procid;

static void kill_and_wait(int pid, int* status)
{
  kill(pid, SIGKILL);
  while (waitpid(-1, status, 0) != pid) {
  }
}

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void use_temporary_dir(void)
{
  char tmpdir_template[] = "./syzkaller.XXXXXX";
  char* tmpdir = mkdtemp(tmpdir_template);
  if (!tmpdir)
    exit(1);
  if (chmod(tmpdir, 0777))
    exit(1);
  if (chdir(tmpdir))
    exit(1);
}

static void __attribute__((noinline)) remove_dir(const char* dir)
{
  DIR* dp = opendir(dir);
  if (dp == NULL) {
    if (errno == EACCES) {
      if (rmdir(dir))
        exit(1);
      return;
    }
    exit(1);
  }
  struct dirent* ep = 0;
  while ((ep = readdir(dp))) {
    if (strcmp(ep->d_name, ".") == 0 || strcmp(ep->d_name, "..") == 0)
      continue;
    char filename[FILENAME_MAX];
    snprintf(filename, sizeof(filename), "%s/%s", dir, ep->d_name);
    struct stat st;
    if (lstat(filename, &st))
      exit(1);
    if (S_ISDIR(st.st_mode)) {
      remove_dir(filename);
      continue;
    }
    if (unlink(filename))
      exit(1);
  }
  closedir(dp);
  if (rmdir(dir))
    exit(1);
}

static void thread_start(void* (*fn)(void*), void* arg)
{
  pthread_t th;
  pthread_attr_t attr;
  pthread_attr_init(&attr);
  pthread_attr_setstacksize(&attr, 128 << 10);
  int i = 0;
  for (; i < 100; i++) {
    if (pthread_create(&th, &attr, fn, arg) == 0) {
      pthread_attr_destroy(&attr);
      return;
    }
    if (errno == EAGAIN) {
      usleep(50);
      continue;
    }
    break;
  }
  exit(1);
}

typedef struct {
  pthread_mutex_t mu;
  pthread_cond_t cv;
  int state;
} event_t;

static void event_init(event_t* ev)
{
  if (pthread_mutex_init(&ev->mu, 0))
    exit(1);
  if (pthread_cond_init(&ev->cv, 0))
    exit(1);
  ev->state = 0;
}

static void event_reset(event_t* ev)
{
  ev->state = 0;
}

static void event_set(event_t* ev)
{
  pthread_mutex_lock(&ev->mu);
  if (ev->state)
    exit(1);
  ev->state = 1;
  pthread_mutex_unlock(&ev->mu);
  pthread_cond_broadcast(&ev->cv);
}

static void event_wait(event_t* ev)
{
  pthread_mutex_lock(&ev->mu);
  while (!ev->state)
    pthread_cond_wait(&ev->cv, &ev->mu);
  pthread_mutex_unlock(&ev->mu);
}

static int event_isset(event_t* ev)
{
  pthread_mutex_lock(&ev->mu);
  int res = ev->state;
  pthread_mutex_unlock(&ev->mu);
  return res;
}

static int event_timedwait(event_t* ev, uint64_t timeout)
{
  uint64_t start = current_time_ms();
  uint64_t now = start;
  pthread_mutex_lock(&ev->mu);
  for (;;) {
    if (ev->state)
      break;
    uint64_t remain = timeout - (now - start);
    struct timespec ts;
    ts.tv_sec = remain / 1000;
    ts.tv_nsec = (remain % 1000) * 1000 * 1000;
    pthread_cond_timedwait(&ev->cv, &ev->mu, &ts);
    now = current_time_ms();
    if (now - start > timeout)
      break;
  }
  int res = ev->state;
  pthread_mutex_unlock(&ev->mu);
  return res;
}

static void sandbox_common()
{
  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = 128 << 20;
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 8 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 0;
  setrlimit(RLIMIT_CORE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 256;
  setrlimit(RLIMIT_NOFILE, &rlim);
}

static void loop();

static int do_sandbox_none(void)
{
  sandbox_common();
  loop();
  return 0;
}

struct thread_t {
  int created, call;
  event_t ready, done;
};

static struct thread_t threads[16];
static void execute_call(int call);
static int running;

static void* thr(void* arg)
{
  struct thread_t* th = (struct thread_t*)arg;
  for (;;) {
    event_wait(&th->ready);
    event_reset(&th->ready);
    execute_call(th->call);
    __atomic_fetch_sub(&running, 1, __ATOMIC_RELAXED);
    event_set(&th->done);
  }
  return 0;
}

static void execute_one(void)
{
  int i, call, thread;
  for (call = 0; call < 16; call++) {
    for (thread = 0; thread < (int)(sizeof(threads) / sizeof(threads[0]));
         thread++) {
      struct thread_t* th = &threads[thread];
      if (!th->created) {
        th->created = 1;
        event_init(&th->ready);
        event_init(&th->done);
        event_set(&th->done);
        thread_start(thr, th);
      }
      if (!event_isset(&th->done))
        continue;
      event_reset(&th->done);
      th->call = call;
      __atomic_fetch_add(&running, 1, __ATOMIC_RELAXED);
      event_set(&th->ready);
      event_timedwait(&th->done, 50);
      break;
    }
  }
  for (i = 0; i < 100 && __atomic_load_n(&running, __ATOMIC_RELAXED); i++)
    sleep_ms(1);
}

static void execute_one(void);

#define WAIT_FLAGS 0

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    char cwdbuf[32];
    sprintf(cwdbuf, "./%d", iter);
    if (mkdir(cwdbuf, 0777))
      exit(1);
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      if (chdir(cwdbuf))
        exit(1);
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000) {
        continue;
      }
      kill_and_wait(pid, &status);
      break;
    }
    remove_dir(cwdbuf);
  }
}

uint64_t r[3] = {0x0, 0xffffffffffffffff, 0xffffffffffffffff};

void execute_call(int call)
{
  intptr_t res = 0;
  switch (call) {
  case 0:
    *(uint32_t*)0x20000080 = 0;
    *(uint64_t*)0x20000088 = 0x20000000;
    *(uint32_t*)0x200000c0 = 8;
    res = syscall(SYS_getsockopt, -1, 0x84, 0x8004, 0x20000080ul, 0x200000c0ul);
    if (res != -1)
      r[0] = *(uint32_t*)0x20000080;
    break;
  case 1:
    *(uint32_t*)0x20000100 = r[0];
    *(uint16_t*)0x20000104 = 4;
    *(uint16_t*)0x20000106 = 8;
    *(uint16_t*)0x20000108 = -1;
    *(uint16_t*)0x2000010a = 9;
    *(uint16_t*)0x2000010c = 9;
    *(uint16_t*)0x2000010e = 7;
    *(uint16_t*)0x20000110 = 1;
    *(uint16_t*)0x20000112 = 0x1f;
    *(uint16_t*)0x20000114 = 0x50;
    *(uint16_t*)0x20000116 = -1;
    *(uint32_t*)0x20000140 = 0x18;
    syscall(SYS_getsockopt, 0xffffff9c, 0x84, 0x901, 0x20000100ul,
            0x20000140ul);
    break;
  case 2:
    syscall(SYS_socket, 0x1cul, 5ul, 0x84);
    break;
  case 3:
    syscall(SYS_socket, 2ul, 2ul, 0x88);
    break;
  case 4:
    res = syscall(SYS_socket, 2ul, 1ul, 0);
    if (res != -1)
      r[1] = res;
    break;
  case 5:
    memcpy((void*)0x20000080,
           "bbr\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
           "\000\000\000\000\000\000\000\000\000\000\000\000\000",
           32);
    *(uint32_t*)0x200000a0 = 0;
    syscall(SYS_setsockopt, r[1], 6, 0x2000, 0x20000080ul, 0x24ul);
    break;
  case 6:
    *(uint32_t*)0x20000040 = 7;
    syscall(SYS_setsockopt, r[1], 6, 1, 0x20000040ul, 4ul);
    break;
  case 7:
    *(uint8_t*)0x200000c0 = 0x34;
    *(uint8_t*)0x200000c1 = 2;
    *(uint16_t*)0x200000c2 = htobe16(0x4e22 + procid * 4);
    *(uint32_t*)0x200000c4 = htobe32(0xfffffffe);
    memset((void*)0x200000c8, 0, 8);
    syscall(SYS_connect, r[1], 0x200000c0ul, 0x10ul);
    break;
  case 8:
    *(uint64_t*)0x20000740 = 0x20000280;
    *(uint8_t*)0x20000280 = 0x10;
    *(uint8_t*)0x20000281 = 2;
    *(uint16_t*)0x20000282 = htobe16(0x4e21 + procid * 4);
    *(uint32_t*)0x20000284 = htobe32(-1);
    memset((void*)0x20000288, 0, 8);
    *(uint32_t*)0x20000748 = 0x10;
    *(uint64_t*)0x20000750 = 0x20000480;
    *(uint64_t*)0x20000480 = 0x20000380;
    *(uint64_t*)0x20000488 = 0;
    *(uint64_t*)0x20000490 = 0x200001c0;
    memcpy(
        (void*)0x200001c0,
        "\x47\x70\x8a\xa2\x6f\x00\x4b\xe1\x78\x9c\x08\xae\xb4\x0d\x0c\x82\x46"
        "\xc8\x88\x89\x8f\x05\x71\xd1\x0a\x00\x18\x57\xac\x20\xdb\x0c\xd8\xe0"
        "\x62\xf2\x48\x24\xe7\x68\x02\x84\x8e\xfb\x21\xe6\xae\xf4\x53\xc4\x6f"
        "\xb7\xd9\x06\x52\x47\x5b\x61\x4a\xe8\x03\xfa\x43\x52\x14\x36\x21\x14"
        "\x34\x9b\x82\x94\x66\x77\xd9\xfd\x14\x2a\xa6\xbb\x61\x70\x33\x77\x0a"
        "\x39\x1d\xbf\xca\x57\x81\xc2\x70\xe3\x68\x98\x3e\x87\x16\x55\x96\x50"
        "\x76\x2d\x28\xe7\xaa\x65\xc9\xd1\xc9\x63\xd2\x1f\x59\x0d\x25",
        117);
    *(uint64_t*)0x20000498 = 0x75;
    *(uint32_t*)0x20000758 = 2;
    *(uint64_t*)0x20000760 = 0;
    *(uint32_t*)0x20000768 = 0;
    *(uint32_t*)0x2000076c = 0;
    syscall(SYS_sendmsg, r[1], 0x20000740ul, 0ul);
    break;
  case 9:
    syscall(SYS_socket, 2ul, 1ul, 0xa);
    break;
  case 10:
    *(uint8_t*)0x20000000 = 0x1c;
    *(uint8_t*)0x20000001 = 0x1c;
    *(uint16_t*)0x20000002 = htobe16(0x4e21 + procid * 4);
    *(uint32_t*)0x20000004 = 0xa1;
    memcpy((void*)0x20000008,
           "\xd4\x4e\xe6\xf4\xb5\x27\xbc\x13\x20\x53\x14\x0c\x9b\x84\x40\x4c",
           16);
    *(uint32_t*)0x20000018 = 0;
    syscall(SYS_connect, -1, 0x20000000ul, 0x1cul);
    break;
  case 11:
    res = syscall(SYS_socket, 0x1cul, 1ul, 0x84);
    if (res != -1)
      r[2] = res;
    break;
  case 12:
    *(uint8_t*)0x20000000 = 0x1c;
    *(uint8_t*)0x20000001 = 0x1c;
    *(uint16_t*)0x20000002 = htobe16(0x4e22 + procid * 4);
    *(uint32_t*)0x20000004 = 0;
    memset((void*)0x20000008, 0, 16);
    *(uint32_t*)0x20000018 = 0;
    syscall(SYS_bind, r[2], 0x20000000ul, 0x1cul);
    break;
  case 13:
    syscall(SYS_setsockopt, r[2], 0x84, 0x1203, 0ul, 0ul);
    break;
  case 14:
    *(uint8_t*)0x200000c0 = 0x1c;
    *(uint8_t*)0x200000c1 = 0x1c;
    *(uint16_t*)0x200000c2 = htobe16(0x4e22 + procid * 4);
    *(uint32_t*)0x200000c4 = 0;
    *(uint64_t*)0x200000c8 = htobe64(0);
    *(uint64_t*)0x200000d0 = htobe64(1);
    *(uint32_t*)0x200000d8 = 0;
    syscall(SYS_connect, r[2], 0x200000c0ul, 0x1cul);
    break;
  case 15:
    syscall(SYS_sendto, r[2], 0ul, 0ul, 1ul, 0ul, 0ul);
    break;
  }
}
int main(void)
{
  syscall(SYS_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x1012ul, -1, 0ul);
  for (procid = 0; procid < 4; procid++) {
    if (fork() == 0) {
      use_temporary_dir();
      do_sandbox_none();
    }
  }
  sleep(1000000);
  return 0;
}
