// https://syzkaller.appspot.com/bug?id=6b67987da83c93586bb6a3f1a69875ec96bb1086
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <pwd.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/endian.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(SYS_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x1012ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000080, "/dev/crypto\000", 12);
  res = syscall(SYS_openat, 0xffffffffffffff9cul, 0x20000080ul, 0ul, 0ul);
  if (res != -1)
    r[0] = res;
  res = syscall(SYS_dup2, r[0], r[0]);
  if (res != -1)
    r[1] = res;
  *(uint32_t*)0x200000c0 = 0;
  *(uint32_t*)0x200000c4 = 0x27;
  *(uint32_t*)0x200000c8 = 0;
  *(uint64_t*)0x200000d0 = 0;
  *(uint32_t*)0x200000d8 = 0x10;
  *(uint64_t*)0x200000e0 = 0x20000000;
  memcpy((void*)0x20000000,
         "\x7d\x1f\xbb\xd1\x37\x9a\x89\xb3\x32\xe1\x66\x78\x90\xe0\x48\x43",
         16);
  *(uint32_t*)0x200000e8 = 0;
  *(uint32_t*)0x200000ec = 0xfdffffff;
  *(uint32_t*)0x200000f0 = 0;
  *(uint32_t*)0x200000f4 = 0;
  *(uint32_t*)0x200000f8 = 0;
  *(uint32_t*)0x200000fc = 0;
  syscall(SYS_ioctl, r[1], 0xc040636aul, 0x200000c0ul);
  *(uint32_t*)0x20001780 = 0;
  *(uint16_t*)0x20001784 = 0;
  *(uint16_t*)0x20001786 = 0;
  *(uint32_t*)0x20001788 = 6;
  *(uint64_t*)0x20001790 = 0x20001440;
  *(uint64_t*)0x20001798 = 0;
  *(uint64_t*)0x200017a0 = 0;
  *(uint64_t*)0x200017a8 = 0;
  syscall(SYS_ioctl, r[1], 0xc0306367ul, 0x20001780ul);
  return 0;
}
