// https://syzkaller.appspot.com/bug?id=4355b4863041401e472c168685754807145afc95
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <pwd.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/endian.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(SYS_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x1012ul, -1, 0ul);
  intptr_t res = 0;
  res = syscall(SYS_socket, 2ul, 1ul, 0);
  if (res != -1)
    r[0] = res;
  *(uint8_t*)0x20000000 = 0x10;
  *(uint8_t*)0x20000001 = 2;
  *(uint16_t*)0x20000002 = htobe16(0x4e23);
  *(uint32_t*)0x20000004 = htobe32(0);
  memset((void*)0x20000008, 0, 8);
  syscall(SYS_bind, r[0], 0x20000000ul, 0x10ul);
  *(uint8_t*)0x20000140 = 0x10;
  *(uint8_t*)0x20000141 = 2;
  *(uint16_t*)0x20000142 = htobe16(0x4e23);
  *(uint32_t*)0x20000144 = htobe32(0);
  memset((void*)0x20000148, 0, 8);
  syscall(SYS_sendto, r[0], 0ul, 0ul, 0ul, 0x20000140ul, 0x10ul);
  syscall(SYS_shutdown, r[0], 1ul);
  {
    int i;
    for (i = 0; i < 32; i++) {
      syscall(SYS_shutdown, r[0], 1ul);
    }
  }
  return 0;
}
