// https://syzkaller.appspot.com/bug?id=0c6b2567feb1563105cd95da2a03a1122bd37890
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <pwd.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/endian.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(SYS_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x1012ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000040, "/dev/crypto\000", 12);
  res = syscall(SYS_openat, 0xffffffffffffff9cul, 0x20000040ul, 0ul, 0ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000440 = 0x10;
  *(uint32_t*)0x20000444 = 0xf;
  *(uint32_t*)0x20000448 = 1;
  *(uint64_t*)0x20000450 = 0x200001c0;
  memset((void*)0x200001c0, 60, 1);
  *(uint32_t*)0x20000458 = 0;
  *(uint64_t*)0x20000460 = 0;
  *(uint32_t*)0x20000468 = 0;
  *(uint32_t*)0x2000046c = 0xddffffff;
  *(uint32_t*)0x20000470 = 0;
  *(uint32_t*)0x20000474 = 0;
  *(uint32_t*)0x20000478 = 0;
  *(uint32_t*)0x2000047c = 0;
  syscall(SYS_ioctl, r[0], 0xc040636aul, 0x20000440ul);
  *(uint32_t*)0x20000180 = 0;
  *(uint16_t*)0x20000184 = 1;
  *(uint16_t*)0x20000186 = 0;
  *(uint32_t*)0x20000188 = 0x10000;
  *(uint32_t*)0x2000018c = 0;
  *(uint32_t*)0x20000190 = 0;
  *(uint64_t*)0x20000198 = 0x20000480;
  *(uint64_t*)0x200001a0 = 0;
  *(uint64_t*)0x200001a8 = 0;
  *(uint64_t*)0x200001b0 = 0x20000140;
  *(uint64_t*)0x200001b8 = 0x20000200;
  syscall(SYS_ioctl, r[0], 0xc040636dul, 0x20000180ul);
  return 0;
}
