// https://syzkaller.appspot.com/bug?id=2d87c3da8c5be955513e6949a11904d660a1a189
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <pwd.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/endian.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(SYS_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x1012ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000180, "/dev/crypto\000", 12);
  res = syscall(SYS_openat, 0xffffffffffffff9cul, 0x20000180ul, 0ul, 0ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000140 = 0x1f;
  *(uint32_t*)0x20000144 = 0x1e;
  *(uint32_t*)0x20000148 = 0x10;
  *(uint64_t*)0x20000150 = 0x200001c0;
  memcpy((void*)0x200001c0,
         "\x3c\x02\x2e\x61\x79\x12\xc6\xaa\xa9\x8e\xb4\x55\x5e\xaa\x35\x05",
         16);
  *(uint32_t*)0x20000158 = 0;
  *(uint64_t*)0x20000160 = 0;
  *(uint32_t*)0x20000168 = 0;
  *(uint32_t*)0x2000016c = 0xfdfffffb;
  *(uint32_t*)0x20000170 = 0;
  *(uint32_t*)0x20000174 = 0;
  *(uint32_t*)0x20000178 = 0;
  *(uint32_t*)0x2000017c = 0;
  syscall(SYS_ioctl, r[0], 0xc040636aul, 0x20000140ul);
  *(uint32_t*)0x20000100 = 0;
  *(uint16_t*)0x20000104 = 1;
  *(uint16_t*)0x20000106 = 0;
  *(uint32_t*)0x20000108 = 0;
  *(uint32_t*)0x2000010c = 0xdd17;
  *(uint32_t*)0x20000110 = 0;
  *(uint64_t*)0x20000118 = 0;
  *(uint64_t*)0x20000120 = 0;
  *(uint64_t*)0x20000128 = 0x20000200;
  *(uint64_t*)0x20000130 = 0x200002c0;
  *(uint64_t*)0x20000138 = 0;
  syscall(SYS_ioctl, r[0], 0xc040636dul, 0x20000100ul);
  return 0;
}
