// https://syzkaller.appspot.com/bug?id=97dda85c86b6445cc003a5c1c08d77bde6e5d937
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <pwd.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/endian.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(SYS_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x1012ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x200003c0, "/dev/crypto\000", 12);
  res = syscall(SYS_openat, 0xffffffffffffff9cul, 0x200003c0ul, 0ul, 0ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000080 = 0;
  *(uint32_t*)0x20000084 = 0xf;
  *(uint32_t*)0x20000088 = 0;
  *(uint64_t*)0x20000090 = 0;
  *(uint32_t*)0x20000098 = 0;
  *(uint64_t*)0x200000a0 = 0;
  *(uint32_t*)0x200000a8 = 0;
  *(uint32_t*)0x200000ac = 0x7d866198;
  *(uint32_t*)0x200000b0 = 0;
  *(uint32_t*)0x200000b4 = 0;
  *(uint32_t*)0x200000b8 = 0;
  *(uint32_t*)0x200000bc = 0;
  syscall(SYS_ioctl, r[0], 0xc040636aul, 0x20000080ul);
  *(uint32_t*)0x20002540 = 0;
  *(uint16_t*)0x20002544 = 0;
  *(uint16_t*)0x20002546 = 0;
  *(uint32_t*)0x20002548 = 0;
  *(uint64_t*)0x20002550 = 0;
  *(uint64_t*)0x20002558 = 0;
  *(uint64_t*)0x20002560 = 0;
  *(uint64_t*)0x20002568 = 0;
  syscall(SYS_ioctl, r[0], 0xc0306367ul, 0x20002540ul);
  return 0;
}
